---
default:
  image: rust

pipeline:
  - name: check, test & release
    steps:
      - name: check
        exec:
          - cargo check
      - name: test
        exec:
          - cargo test test_hello_world
      - name: release
        exec:
          - cargo build --release
