---
pipeline:
  - name: cargo check
    steps:
      - exec: cargo check
  - name: cargo test
    steps:
      - exec: cargo test
  - name: cargo build
    steps:
      - exec: cargo build --release
artifacts:
  - target/release/fake-ci