---
default:
  image: rust

pipeline:
  - name: check, test & release
    env:
      RUST_LOG: trace
    steps:
      - name: check
        exec:
          - cargo check
      - name: test
        exec:
          - cargo test test_hello_world
      - name: release
        exec:
          - cargo build --release
  - name: Docker
    image: docker:dind
    steps:
      - name: build
        exec:
          - docker build -t paulollivier/fake-ci:latest .
      - name: publish
          - echo -n "$DOCKER_HUB_PASSWORD" | docker login -u paulollivier --password-stdin
          - docker push paulollivier/fake-ci:latest
