---
pipeline:
  - name: check, test & release
    steps:
      - name: check
        exec:
          - cargo check
      - name: test
        exec:
          - cargo test
      - name: release
        exec:
          - cargo build --release
artifacts:
  - target/release/fake-ci