version: "3"
services:
  fake-ci:
    image: paulollivier/fake-ci:latest
    container_name: fake-ci
    labels:
      - "com.centurylinklabs.watchtower.scope=fakeci"
    volumes:
      - ./watch_fakeci.yml:/app/fake-ci.yml
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  watchtower:
    image: containrrr/watchtower
    environment:
      TZ: Europe/Paris
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_SCOPE: fakeci
      WATCHTOWER_POLL_INTERVAL: 600
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.scope=fakeci"
